# permissions for end users to edit etcdbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: etcdbackup-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: weiyuanke-etcd-operator
    app.kubernetes.io/part-of: weiyuanke-etcd-operator
    app.kubernetes.io/managed-by: kustomize
  name: etcdbackup-editor-role
rules:
- apiGroups:
  - etcd.hcs.io
  resources:
  - etcdbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - etcd.hcs.io
  resources:
  - etcdbackups/status
  verbs:
  - get
