---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - etcd.hcs.io
  resources:
  - etcdbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - etcd.hcs.io
  resources:
  - etcdbackups/finalizers
  verbs:
  - update
- apiGroups:
  - etcd.hcs.io
  resources:
  - etcdbackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - etcd.hcs.io
  resources:
  - etcdclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - etcd.hcs.io
  resources:
  - etcdclusters/finalizers
  verbs:
  - update
- apiGroups:
  - etcd.hcs.io
  resources:
  - etcdclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - etcd.hcs.io
  resources:
  - etcdrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - etcd.hcs.io
  resources:
  - etcdrestores/finalizers
  verbs:
  - update
- apiGroups:
  - etcd.hcs.io
  resources:
  - etcdrestores/status
  verbs:
  - get
  - patch
  - update
