apiVersion: etcd.hcs.io/v1beta2
kind: EtcdRestore
metadata:
  labels:
    app.kubernetes.io/name: etcdrestore
    app.kubernetes.io/instance: etcdrestore-sample
    app.kubernetes.io/part-of: weiyuanke-etcd-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: weiyuanke-etcd-operator
  name: etcdrestore-sample
spec:
  # TODO(user): Add fields here
